### Recuperar todos los productos
GET http://localhost:3000/productos

### Recuperar un producto por id
GET http://localhost:3000/productos/6

### Recuperar todos los productos por su tipo
GET http://localhost:3000/productos?tipo=remeras

### Crear un produto con POST
POST http://localhost:3000/productos
Content-Type: application/json

{
    "name": "el Diego",
    "precio": 3500,
    "calibre": "473ml",
    "estilo": "Goleador",
    "sabor": "DUlce",
    "alcohol": 6,
    "IBU": 38,
    "descripcion": "Cerveza dorada, de aroma dulce y carácter suave a malta. Sabor a lúpulo moderado y bajo amargor. Una experiencia suave y grata donde la malta se expresa con simpleza y frescura",
    "imagen": ["/img/cervezas/golden1.webp", "/img/cervezas/golden2.webp"],
    "cantidad": 100,
    "premios": ["Medalla de Plata Copa Argentina 2016 "],
    "tipo": "cervezas"
  }

### Borrar un producto
DELETE http://localhost:3000/productos/2


### Actualizar una película
PATCH http://localhost:3000/productos/1
Content-Type: application/json

{
  "name": 2022
}