### getAll

GET http://localhost:3000/micuenta/usuarios

### getbyID

GET http://localhost:3000/micuenta/01c523ac-32f2-11ef-9404-cecd028ee826

### getbyUsuarios

GET http://localhost:3000/micuenta/usuarios/usuario2

### crear

DELETE http://localhost:3000/micuenta/407a6a10-3322-11ef-9404-cecd028ee826

### update

PATCH http://localhost:3000/micuenta/68b1ea84-3322-11ef-9404-cecd028ee826
Content-Type: application/json

{
    "username": "usuario1"
}

###post 
POST http://localhost:3000/micuenta/register
Content-Type: application/json

{
    "username": "usuario3",
    "password": "123456",
    "rol": "cliente"
}